version: '3.6'

volumes:
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus
   #   - prometheus-data:/prometheus
    command: 
     # --web.enable-lifecycle  
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3060:3000"
    volumes: 
      -  grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file: 
      - ./grafana/config.monitoring
    restart: always



#volumes:
 # prometheus-data:

