version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    volumes:
      - ./prometheus/:/etc/prometheus
   #   - prometheus-data:/prometheus
    command: 
     # --web.enable-lifecycle  
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9000:9090"

  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3060:3000"

#volumes:
 # prometheus-data:

