global:
  scrape_interval:     5s

scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
  - targets: ['localhost:9090' ,                                                                                                                                                                                                                                                                                                                              'devops-project-cd.herokuapp.com']


                                                                                                                                                                                                                                                                                                                                