global:
  scrape_interval:     5s

scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
  - targets: ['devops-project-cd.herokuapp.com']


                                                                                                                                                                                                                                                                                                                                