{
 "title": "projet devops",
 "time": { "from": "2021-01-27T09:11:30.890Z", "to": "2021-01-27T21:11:30.890Z" },
 "panels": [
  {
   "title": "process_resident_memory_bytes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "django_http_responses_total_by_status_view_method_created",
   "type": "graph",
   "gridPos": { "h": 23, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total"
    }
   ]
  },
  {
   "title": "django_http_requests_total_by_method_total",
   "type": "graph",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total"
    }
   ]
  }
 ]
}